name: 🐛Bug 报告
description: 提交 Bug 以帮助我们提高Mod体验
title: "[Bug] 我的标题"
assignees: kitUIN
labels:
  - "bug"
body:
  - type: markdown
    attributes:
      value: |
        ## 写在开头
        🚨 请务必完整填写下面的内容，如果缺少必要的信息，开发者可能会在未调查的情况下直接关闭问题 🚨

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Bug 描述
      description: 请简短的描述你遇到的问题
  - type: textarea
    id: repro-steps
    validations:
      required: true
    attributes:
      label: 复现问题的步骤
      render: plain text
      description: 请提供复现问题的步骤，如果不能，请写明原因
      placeholder: |
        干净清晰的复现步骤有助于开发者更快定位问题所在，你所遇到的问题也会获得更高的优先级.

        示例步骤:
        1. 进入一个新世界
        3. 点击 '....'
        4. 滚动至 '....'
        5. 发现问题

  - type: textarea
    validations:
      required: true
    attributes:
      label: 日志记录
      description: 请打开日志文件夹，选取问题发生当日的日志记录(如latest.log)作为 Issue 的附件上传
  - type: dropdown
    id: mod-loader
    validations:
      required: true
    attributes:
       label: 模组加载器
       description: 选择一个你发现问题的加载器类型
       options:
         - Forge
         - Fabric
         - NeoForge
         - Quilt
  - type: dropdown
    id: mc-version
    validations:
      required: true
    attributes:
       label: 我的世界版本
       description: 选择一个你发现问题的MC版本
       options:
         - 1.21.x
         - 1.20.5/1.20.6
         - 1.20.3/1.20.4
         - 1.20/1.20.1/1.20.2
         - 1.19.3/1.19.4
         - 1.19.1/1.19.2
         - 1.19
         - 1.18.x
         - 1.17.x
         - 1.16.x
  - type: textarea
    validations:
      required: true
    attributes:
      label: Mod版本
      description: 你发现问题的Mod版本
      placeholder: |
        Mod版本号
  - type: textarea
    validations:
      required: true
    attributes:
      label: 电脑系统|JAVA版本
      description: 你的电脑系统与JAVA版本
  - type: textarea
    id: serverVersion
    attributes:
      label: 服务器版本
      description: 如果在服务器上出错,请提供服务器核心版本号
  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: 如果可以，提交截图更有助于我们分析问题


  - type: textarea
    id: additional-context
    attributes:
      label: 备注
      description: 添加你认为有必要的信息
