name: 测试Fabric(jar)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:

  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate Matrix
        id: set-matrix
        run: |
          chmod 777 matrix.sh
          ./matrix.sh -path "fabric"

  build:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Chose JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Read version.txt and save to variable
        run: |
          mod_version=$(cat version.txt)
          echo "Version: $mod_version"
          echo "MOD_VERSION=$mod_version" >> "$GITHUB_ENV"
      - name: Init Files
        run: |
          chmod 777 init.sh && ./init.sh
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ matrix.config.mc-version }}+${{ matrix.config.mc-loader }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ matrix.config.mc-version }}+${{ matrix.config.mc-loader }}-gradle-
      - name: Build
        run: |
          cd ${{ matrix.config.mc-loader }}/${{ matrix.config.mc-loader }}-${{ matrix.config.mc-version }}
          chmod 777 gradlew && ./gradlew clean build
          cd ../..
      - uses: actions/upload-artifact@v4
        with:
          name: ChatImage-${{ env.MOD_VERSION }}+${{ matrix.config.mc-version }}+${{ matrix.config.mc-loader }}.jar
          path: ChatImage-jar/${{ env.MOD_VERSION }}/ChatImage-${{ env.MOD_VERSION }}+${{ matrix.config.mc-version }}+${{ matrix.config.mc-loader }}.jar
